(define (problem car_prob)
    (:domain car)
    (:init (= s 0) (not (engineBlown))
            (running)
	    (transmission_fine)
	    (= (running_time) 0)
	    (= (up_limit) 2)
	    (= (down_limit) -2)
            (= d 0)
            (= a 0)
            (= v 0))
     (:goal (and (< (s) 4) (goal_reached) (not(engineBlown)) (<= (running_time) 50) (transmission_fine) ))
     (:metric minimize(total-time))
)
